#!/usr/bin/env php
<?php

use Ratchet\Http\HttpServer;
use Ratchet\Server\IoServer;
use Ratchet\WebSocket\WsServer;

set_time_limit(0);
ini_set('memory_limit', '-1');
ini_set('error_log', __DIR__ . '/../var/log/php.log');

$loader = require_once __DIR__ . '/vendor/autoload.php';

$webSocketServer = new \LightWebSocket\Server();

$server = IoServer::factory(
    new HttpServer(
        new WsServer(
            $webSocketServer
        )
    ),
    8087
);
$server->run();